### ISSUE TITLE
PHP Package Checklist

### ISSUE THREAD

**Issue by hannesvdvreken** [aloha/laravel-twilio#42]
http://phppackagechecklist.com/#1,2,3,4,5,6,8,9,10,12,13,14

To do:
- [x] 1: Pick a name wisely (aloha/twilio)
- [x] 2: Host source openly (https://github.com/aloha/laravel4-twilio)
- [x] 3: PSR-4 auto loading (#37)
- [x] 4: Distribute with composer.
- [x] 5: Framework agnostic
    - [x] Don't use anything framework specific inside Manager, Twilio and Interface, so these can be used in any framework.
    - [x] Move Service Provider and Facade into Support namespace (Commands are OK where they are).
- [x] 6: PSR-2 is mostly applied everywhere, but run php-cs-fixer or phpcs to be 100% sure.
- [ ] 7: Write unit tests (#40). Let's try and get 50% code coverage to start with and go from there.
- [x] 8: Docblock your code.
- [x] 9: Use semver.
- [x] 10: [Keep a changelog](http://keepachangelog.com)(#38). Currently a lot has changed. Time to write a list of what has changed.
- [x] 11: [CI] Travis is enabled, but builds doesn't run tests, and we could use Scrutinizer to guard PSR-2 code style.
- [x] 12: Extensive documentation (in README is a good place, but every method needs to be documented)(#38).
- [x] 13: Include a license
- [x] 14: Add `CONTRIBUTING` file and explain the code style, testing and PR process.
